replicaCount: 1

namespace:
  create: false

image:
  repository: registry.gitlab.com/modanisatech/marketplace/payment-mf
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred

fullnameOverride: "payment-mf"

ports:
  - name: http
    protocol: TCP
    containerPort: 3000
    servicePort: 80

configMap:
  APP_ENV: phoenix
  NODE_ENV: phoenix

istio:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: ${LB_ENDPOINT}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      path: "/"
      hosts:
        - marketplace-payment-mf-phoenix.modanisa.net
      tls: {}
      corsPolicy:
        allowOrigins:
          - regex: "(.*?).modanisa.net"
          - regex: "(.*?).modanisatest.com"
          - regex: "(.*?).modanisa.com"
        allowMethods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          - OPTIONS
        allowCredentials: false
        allowHeaders:
          - "*"
        maxAge: "24h"
  auth:
    enabled: false
  ratelimit:
    enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: "/"
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: "/"
    port: http
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m
